updated workflows

diff --git a/.github/workflows/sign_views.yaml b/.github/workflows/sign_views.yaml
--- a/.github/workflows/sign_views.yaml
+++ b/.github/workflows/sign_views.yaml
@@ -37,6 +37,10 @@ jobs:
                         minified_dir="minified/$(dirname "$relative_path")"
                         mkdir -p "$minified_dir"
                         terser "$file" -o "$minified_dir/$(basename "$file")"
+                        if [ $? -ne 0 ]; then
+                            echo "Invalid JS file $file" >&2
+                            exit 1
+                        fi
                         echo "Minified $file"
                     done' sh {} +
 
diff --git a/.github/workflows/verify.yaml b/.github/workflows/verify.yaml
--- a/.github/workflows/verify.yaml
+++ b/.github/workflows/verify.yaml
@@ -31,4 +31,8 @@ jobs:
                             exit 1 
                         fi
                         terser "$file" 1> /dev/null
+                        if [ $? -ne 0 ]; then
+                            echo "Invalid JS file $file" >&2
+                            exit 1
+                        fi
                     done' sh {} +
